# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: PowerShell@2
  inputs:
    filePath: 'build/build.ps1'
    arguments: 'Default'
  displayName: 'Run psake Analyse'

- script: dotnet --version
  displayName: 'Run a one-line script'

- pwsh: |
    Install-Module -Name 'AWSLambdaPSCore' -RequiredVersion '2.0.0.0' -Scope CurrentUser -Force
    Import-Module -Name 'AWSLambdaPSCore'
    New-AWSPowerShellLambdaPackage -ScriptPath $scriptPath -OutputPackage '/tmp/lambda.zip'
  displayName: 'test build'
